### ISSUE TITLE
Make "show in orga phonebook" optional

### ISSUE THREAD

**Issue by n-st** [eventphone/guru3#20]
**Is your feature request related to a problem? Please describe.**

Currently …
1. users can create extensions in the orga range (1xxx) only after activating an orga token on the current Guru account,
2. all personal extensions are shown in the orga phonebook after activating an orga token on the current Guru account.

It is somewhat inconvenient that the user has to accept 2 to achieve 1.

**Describe the solution you'd like**

It would be helpful if extensions could be marked/unmarked as "is orga-related" (i.e. "show in orga phonebook") individually (rather than just showing all of the user's extensions).

Perhaps that's just one extra database column and checkbox away? :)

**Describe alternatives you've considered**

The current recommendation for hiding the user's private extensions from the other orga members is to create and use two separate accounts (one for private use, one with the orga activation).
This technically works, but requires frequent logout-logins and leads to confusion when the user needs to be added as a callgroup administrator ("which of your two usernames was the correct one again?").

**Comment by garw** [comment]
Thanks for your input.

This design was/is a deliberate choice. It is motivated by simplicity and reduces potential misconfiguration of orga/non-orga extensions due to a strict and visible separation.

Moreover, organizers have the option to lend phones from us on onsite events. This should only be used for official and not for private purposes and should not be easily circumventable by unchecking some check-boxes.
